-- Initialize pgvector extension
CREATE EXTENSION IF NOT EXISTS vector;

-- Grant permissions to user
GRANT ALL PRIVILEGES ON DATABASE seiji_watch TO seiji_watch_user;
GRANT ALL ON SCHEMA public TO seiji_watch_user;

-- Create basic tables (will be managed by Alembic migrations later)
-- This is just for initial development setup

-- Test table to verify pgvector is working
CREATE TABLE IF NOT EXISTS test_embeddings (
    id SERIAL PRIMARY KEY,
    content TEXT NOT NULL,
    embedding vector(1536),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Note: Skipping test data insertion as it requires 1536-dimensional vectors
-- Real embeddings will be generated by the application using OpenAI's text-embedding-3-large model